In [1]:
import pandas as pd
import sqlite3

In [2]:
df=pd.read_csv("../Data/Cleaned/hr_cleaned.csv")
conn = sqlite3.connect("../mySql/hr_analytics.db")
df.to_sql("employee_data",conn,if_exists="replace",index=False
)

100000

In [3]:
query=""" SELECT COUNT(*) AS total_employees
FROM employee_data
GROUP BY Attrition;
"""
pd.read_sql_query(query,conn)#test sql table

   total_employees
0            83919
1            16081

In [4]:
query = """
SELECT ROUND(SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),2) AS attrition_rate
FROM employee_data;
"""
pd.read_sql_query(query, conn)#attrition rate

   attrition_rate
0           16.08

In [5]:
query = """
SELECT Department, COUNT(*) AS attrition_count
FROM employee_data
WHERE Attrition = 'Yes'
GROUP BY Department
ORDER BY attrition_count DESC;
"""

pd.read_sql_query(query, conn)#Department-wise attrition

               Department  attrition_count
0  Research & Development             9032
1                   Sales             6240
2         Human Resources              809

In [6]:
query = """
SELECT OverTime, Attrition, COUNT(*) AS total
FROM employee_data
GROUP BY OverTime, Attrition
ORDER BY OverTime, Attrition;
"""

pd.read_sql_query(query, conn)#Overtime impact

  OverTime Attrition  total
0       No        No  64358
1       No       Yes   7457
2      Yes        No  19561
3      Yes       Yes   8624

In [7]:
query = """
SELECT JobRole, ROUND(AVG(MonthlyIncome), 2) AS avg_salary
FROM employee_data
GROUP BY JobRole
ORDER BY avg_salary DESC;
"""

pd.read_sql_query(query, conn)#Average salary by job role

                     JobRole  avg_salary
0                    Manager    17190.69
1          Research Director    16002.51
2  Healthcare Representative     7507.24
3     Manufacturing Director     7288.93
4            Sales Executive     6920.22
5            Human Resources     4250.78
6      Laboratory Technician     3240.93
7         Research Scientist     3233.52
8       Sales Representative     2628.82